plugins {
    id("java")
    id("org.owasp.dependencycheck") version "12.2.0"
}

apply(from = "$rootDir/gradle/checkstyle.gradle")

dependencies {
    compileOnly("io.opentelemetry:opentelemetry-sdk")
    compileOnly("io.opentelemetry.semconv:opentelemetry-semconv")
    compileOnly("io.opentelemetry:opentelemetry-sdk-extension-autoconfigure")
    compileOnly("io.opentelemetry.javaagent:opentelemetry-javaagent-extension-api")
    compileOnly("io.opentelemetry.javaagent:opentelemetry-javaagent-tooling")

    testImplementation("io.opentelemetry.semconv:opentelemetry-semconv")
    testImplementation("io.opentelemetry:opentelemetry-sdk-extension-autoconfigure-spi")
    testImplementation("io.opentelemetry.javaagent:opentelemetry-testing-common")
    testImplementation("io.opentelemetry.javaagent:opentelemetry-javaagent-extension-api")
}

configure<org.owasp.dependencycheck.gradle.extension.DependencyCheckExtension> {
    skipConfigurations = listOf("checkstyle", "annotationProcessor")
    suppressionFile = "buildscripts/dependency-check-suppressions.xml"
    failBuildOnCVSS = 7.0f // fail on high or critical CVE
}

fun updateGeneratedFile(file: File, newContent: String) {
    if (System.getenv("CHECK_GENERATED_FILES") == "true") {
        val oldContent = file.readText()
        if (oldContent != newContent) {
            throw GradleException("File ${file} was modified in CI. Please update it locally and commit.")
        }
    } else {
        project.mkdir(file.parentFile)
        file.writeText(newContent)
    }
}

tasks.register("manageVersionClass") {
    doLast {
        updateGeneratedFile(
            File("${projectDir}/src/main/java/com/grafana/extensions/resources/internal", "DistributionVersion.java"),
            """/*
 * Copyright Grafana Labs
 * SPDX-License-Identifier: Apache-2.0
 */

package com.grafana.extensions.resources.internal;

// This class is generated by custom/build.gradle.kts.  Do not edit.

public class DistributionVersion {

  public static final String VERSION = "$version";
}
"""
        )
    }
}

tasks.named("compileJava") {
    dependsOn("manageVersionClass")
}
